# -*- coding: utf-8 -*-
"""map_mark

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzxpSDSFqUYybA1poRalGtT7t7wqIfHM
"""

import folium
import pandas as pd
import sys
from folium import IFrame
import io
from PIL import Image
import boto3
from botocore.exceptions import ClientError


def map_mark(input,r):
  base = input[0]
  base_map = folium.Map(location=[base[1], base[2]], zoom_start=15)
  folium.Circle(
    radius=r*1000+50,
    location=(base[1],base[2]),
    popup='The Waterfront',
    color='crimson',
    fill=False,
  ).add_to(base_map)
  linelist = []
  #              出發點的標記  html亂碼轉中文
  incidents = folium.map.FeatureGroup()
  heading3 = """<h6>{}</h6>""".format
  iframe = IFrame(html = heading3(utf2asc(base[0])),width=150,height=30)
  popup = folium.Popup(iframe)
  folium.Marker([base[1],base[2]],popup= popup, icon=folium.Icon(color='red')).add_to(base_map)
  linelist.append((base[1],base[2]))
  #
  for i in range(1,len(input)):
    iframe = IFrame(html = heading3(utf2asc(input[i][0])),width=150,height=30)
    popup = folium.Popup(iframe)
    folium.Marker([input[i][1],input[i][2]],popup= popup, icon=folium.Icon(color='red')).add_to(base_map)
    linelist.append((input[i][1],input[i][2]))
    if i!=len(input)-1 and i!=1:
      folium.PolyLine(linelist[i-1:i+1],"{}".format(i),color = 'blue',weight = 2 , opacity = 1).add_to(base_map)
    elif i==1:
      folium.PolyLine(linelist[i-1:i+1],"{}".format(i),color = 'green',weight = 2 , opacity = 1).add_to(base_map)
    else:
      folium.PolyLine(linelist[i-1:i+1],"{}".format(i),color = 'red',weight = 2 , opacity = 1).add_to(base_map)
    base_map.add_child(incidents)

  return base_map

def utf2asc(s):
    return str(str(s).encode('ascii', 'xmlcharrefreplace'))[2:-1]


def map_to_s3(input_list, radius):
	'''
		input :  
			input_list : list of list
					[['白鬍子牛排', 24.79856998883122, 120.99786995956578],
					['99元外帶牛排套餐', 24.798339797994373, 120.99781348118799],
					['松原無煙鐵板燒', 24.798300007729935, 120.99794003227629],
					['港島主麵', 24.79792001414947, 120.99634998524391],
					['慢點吐司', 24.79794997945332, 120.99646003963261],
					]
			radius : float means the raidus to find (km)
		upload .html file to AWS S3 bucket
	'''
	file_map = map_mark(input_list, radius)

	s3 = boto3.client('s3', region_name='us-east-1')
	file_map.save('./utils_py/index.html')

	s3.upload_file('./utils_py/index.html', 'pl-instamap', 'index.html', ExtraArgs = {
                 # Set proper content type
                 'ContentType':'text/html',
                 # Set proper ACL
                 'ACL': "public-read"})




if __name__=='__main__':
	input = [['白鬍子牛排', 24.79856998883122, 120.99786995956578],
	['99元外帶牛排套餐', 24.798339797994373, 120.99781348118799],
	['松原無煙鐵板燒', 24.798300007729935, 120.99794003227629],
	['港島主麵', 24.79792001414947, 120.99634998524391],
	['慢點吐司', 24.79794997945332, 120.99646003963261],
	]
	file_map = map_to_s3(input, 0.5)

